const ActivityTypes = {
    // Board activities
    BOARD_CREATED: 'BOARD_CREATED',
    BOARD_UPDATED: 'BOARD_UPDATED',
    BOARD_MEMBER_ADDED: 'BOARD_MEMBER_ADDED',
    BOARD_MEMBER_REMOVED: 'BOARD_MEMBER_REMOVED',
    BOARD_MEMBER_ROLE_CHANGED: 'BOARD_MEMBER_ROLE_CHANGED',

    // List activities
    LIST_CREATED: 'LIST_CREATED',
    LIST_UPDATED: 'LIST_UPDATED',
    LIST_DELETED: 'LIST_DELETED',
    LIST_MOVED: 'LIST_MOVED',

    // Card activities
    CARD_CREATED: 'CARD_CREATED',
    CARD_UPDATED: 'CARD_UPDATED',
    CARD_DELETED: 'CARD_DELETED',
    CARD_MOVED: 'CARD_MOVED',
    CARD_ASSIGNED: 'CARD_ASSIGNED',
    CARD_UNASSIGNED: 'CARD_UNASSIGNED',
    CARD_COMPLETED: 'CARD_COMPLETED',
    CARD_UNCOMPLETED: 'CARD_UNCOMPLETED',
    CARD_DUE_DATE_SET: 'CARD_DUE_DATE_SET',
    CARD_DUE_DATE_CHANGED: 'CARD_DUE_DATE_CHANGED',
    CARD_DUE_DATE_REMOVED: 'CARD_DUE_DATE_REMOVED',
    CARD_ATTACHMENT_ADDED: 'CARD_ATTACHMENT_ADDED',
    CARD_ATTACHMENT_REMOVED: 'CARD_ATTACHMENT_REMOVED',

    // Comment activities
    COMMENT_ADDED: 'COMMENT_ADDED'
};

const EntityTypes = {
    BOARD: 'board',
    LIST: 'list',
    CARD: 'card',
    COMMENT: 'comment'
};

const PAGE_SIZE = 10;

module.exports = {
    ActivityTypes,
    EntityTypes,
    PAGE_SIZE
};
